apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: hostpath-container
    image: nginx
    volumeMounts:
    - mountPath: /foo
      name: example-volume
      readOnly: true
  volumes:
  - name: example-volume
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /tmp/hostpath # directory location on host
      type: DirectoryOrCreate # this field is optional