---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: vproapp
  ports:
  - port: 8090
    nodePort: 30001
    targetPort: vproapp-port
    protocol: TCP
  type: NodePort