services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: wiliangdev/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  memcache:
    image: memcached:latest
    container_name: vprocache01
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:4.0
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: wiliangdev/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vprodbdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: wiliangdev/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}